# The URL the site will be built for
base_url = "https://rajeshrah22.github.io"
title = "Rahul's blog site"
description = "Reads like an engineering journal"
compile_sass = true
generate_feeds = true
feed_limit = 10
feed_filenames = ["atom.xml"]
taxonomies = [{ name = "tags" }]
theme = "zolanight"

[markdown.highlighting]
theme = "catppuccin-latte" # Code highlighting theme

[extra.zolanight]
theme = "tokyoday"
home_list_latest_blog_posts = true
google_analytics_id = "G-7NC6GLJCFS"
ko_fi_url = "https://ko-fi.com/mxaddict"
